# Generated by Django 4.2.5 on 2023-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('raison', models.CharField(choices=[('Cybercriminel', 'Cybercriminel'), ('Drogue', 'Drogue'), ('Red room', 'Red room'), ('Trafique', 'Trafique'), ('Autre', 'Autre')], max_length=255)),
            ],
        ),
    ]
