# Generated by Django 4.2.5 on 2023-10-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_approuveddomaine_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsreclamation',
            name='traiter',
            field=models.BooleanField(default=False),
        ),
    ]
