# Generated by Django 4.2.5 on 2023-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dnsreclamation_traiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsreclamation',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
