# Generated by Django 4.2.5 on 2023-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dnsreclamation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='approuveddomaine',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
